{{- if and (eq .Values.authz.mode "external") .Values.authz.external.bearerTokenSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.authz.external.bearerTokenSecret.name }}
  labels:
{{ include "lm-serve-platform.labels" . | indent 4 }}
type: Opaque
stringData:
  {{ .Values.authz.external.bearerTokenSecret.key }}: {{ .Values.authz.external.bearerTokenSecret.value | quote }}
{{- end }}