{{- if .Values.modelPublisherRbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.modelPublisherRbac.serviceAccountName }}
  labels:
{{ include "lm-serve.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.modelPublisherRbac.serviceAccountName }}
  labels:
{{ include "lm-serve.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: [{{ .Values.catalog.name | quote }}]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.modelPublisherRbac.serviceAccountName }}
  labels:
{{ include "lm-serve.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.modelPublisherRbac.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.modelPublisherRbac.serviceAccountName }}
{{- end }}
