---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.publisher.globalCatalogConfigMapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.publisher.name }}
    app.kubernetes.io/component: catalog
    app.kubernetes.io/part-of: lm-serve-publisher
data:
  {{ .Values.publisher.globalCatalogKey }}: |
{{ .Files.Get (printf "catalogs/%s" .Values.publisher.globalCatalogFile) | nindent 4 }}
{{- range .Values.consumer.catalogs }}
{{- if (default true .enabled) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.publisher.catalogConfigMapPrefix }}-{{ .tenant }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Values.publisher.name }}
    app.kubernetes.io/component: catalog
    app.kubernetes.io/part-of: lm-serve-publisher
data:
  {{ $.Values.publisher.catalogKey }}: |
{{ $.Files.Get (printf "catalogs/%s" .file) | nindent 4 }}
{{- end }}
{{- end }}
