{{- if eq .Values.secrets.mode "create" }}
{{- if or (eq (len .Values.secrets.apiKeys) 0) (eq .Values.secrets.jwtSecret "") }}
{{- fail "secrets.apiKeys and secrets.jwtSecret are required when secrets.mode=create" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.existingSecretName }}
  labels:
{{ include "lm-serve-auth.labels" . | indent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.keys.apiKeys }}: |
{{- range .Values.secrets.apiKeys }}
    {{ . }}
{{- end }}
  {{ .Values.secrets.keys.jwtSecret }}: {{ .Values.secrets.jwtSecret | quote }}
{{- end }}
